name: My First Workflow

on: push

jobs:
  first_job:  
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Message
        run: echo "Welcome to the world of Learning. This is My First Job!!"

      - name: Current Working Directory
        run: pwd

      - name: List all files
        run: ls -lart
      
      - name: Read file
        run: cat README.md

      # - name: Checkout Repo
      #   uses: actions/checkout@v4
        
      # - name: List and Read files
      #   run: |
      #     echo "My First GitHub Action Job"
      #     ls -ltra
      #     cat README.md
      
      # - name: Generate ASCII Artwork
      #   run: cowsay -f dragon "Run for cover, I am a DRAGON......RAWR" >> dragon.txt