name: Generate ASCII Artwork

on: push

jobs:
  build_job:  
    runs-on: ubuntu-latest
    steps:
        - name: OS Version
          run: cat /etc/os-release     

  test_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
        - name: Current Working Directory
          run: pwd

  deploy_job:
    runs-on: ubuntu-latest
    needs: [build_job, test_job]
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: List all files
          run: ls -lart 

        - name: Execute Script 
          run: |
            chmod +x generate-ascii.sh
            ./generate-ascii.sh

        - name: Check if the dragon file exists
          run: ls | grep -i dragon.txt
    #   - name: Install Cowsay
    #     run: sudo apt-get install cowsay -y 
        
    #   - name: Generate ASCII Artwork
    #     run: cowsay -f dragon "Run for cover, I am a DRAGON......RAWR" >> dragon.txt
    
    #   - name: List all files
    #     run: ls -lart
      
    #   - name: Displaying Artwork
    #     run: cat dragon.txt
              
