name: Generate ASCII Artwork

on: push

jobs:
  build_job:  
    runs-on: ubuntu-latest
    steps:
        - name: OS Version
          run: cat /etc/os-release     

        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Execute Script 
          run: |
            chmod +x generate-ascii.sh
            ./generate-ascii.sh

        - name: Upload Dragon text file
          uses: actions/upload-artifact@v4
          with:
            # Name of the artifact to upload.
            # Optional. Default is 'artifact'
            name: dragon-text-file
            path: dragon.txt
            
  test_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
        - name: Current Working Directory
          run: pwd

        - name: Download Dragon text file
          uses: actions/download-artifact@v4
          with:
            # Name of the artifact to download.
            # If unspecified, all artifacts for the run are downloaded.
            # Optional.
            name: dragon-text-file
          
        - name: Check if the dragon file exists
          run: ls | grep -i dragon.txt

  deploy_job:
    runs-on: ubuntu-latest
    needs: [build_job, test_job]
    steps:
        - name: Download Dragon text file
          uses: actions/download-artifact@v4
          with:
            # Name of the artifact to download.
            # If unspecified, all artifacts for the run are downloaded.
            # Optional.
            name: dragon-text-file
          
        - name: List all files
          run: ls -lart 

        - name: View dragon file
          run: cat dragon.txt
          
    #   - name: Install Cowsay
    #     run: sudo apt-get install cowsay -y 
        
    #   - name: Generate ASCII Artwork
    #     run: cowsay -f dragon "Run for cover, I am a DRAGON......RAWR" >> dragon.txt
    
    #   - name: List all files
    #     run: ls -lart
      
    #   - name: Displaying Artwork
    #     run: cat dragon.txt
              
